export const batteryFields = [
  {
    name: 'batteryAge',
    label: 'Battery Age',
    unit: 'years',
    min: 0,
    max: 30,
    step: 0.1,
  },
  {
    name: 'chargingCycles',
    label: 'Charging Cycles',
    unit: 'cycles',
    min: 0,
    max: 20000,
    step: 1,
  },
  {
    name: 'chargingFrequency',
    label: 'Charging Frequency',
    unit: 'per week',
    min: 0,
    max: 20,
    step: 0.1,
  },
  {
    name: 'fastChargingUsage',
    label: 'Fast Charging Usage',
    unit: '%',
    min: 0,
    max: 100,
    step: 0.1,
  },
  {
    name: 'averageTemperature',
    label: 'Average Temperature',
    unit: 'C',
    min: -40,
    max: 90,
    step: 0.1,
  },
  {
    name: 'chargingDuration',
    label: 'Charging Duration',
    unit: 'hours',
    min: 0,
    max: 24,
    step: 0.1,
  },
  {
    name: 'dailyDistance',
    label: 'Daily Distance',
    unit: 'km',
    min: 0,
    max: 1500,
    step: 0.1,
  },
  {
    name: 'socHistory',
    label: 'SOC History',
    unit: '%',
    min: 0,
    max: 100,
    step: 0.1,
  },
  {
    name: 'batteryCapacity',
    label: 'Battery Capacity',
    unit: 'kWh',
    min: 1,
    max: 300,
    step: 0.1,
  },
  {
    name: 'voltage',
    label: 'Voltage',
    unit: 'V',
    min: 0,
    max: 1200,
    step: 0.1,
  },
  {
    name: 'current',
    label: 'Current',
    unit: 'A',
    min: -1000,
    max: 1000,
    step: 0.1,
  },
];

export const defaultBatteryValues = Object.fromEntries(batteryFields.map((field) => [field.name, '']));
