/**
 * Real-world EV vehicle database with manufacturer battery specs.
 * Data sourced from official manufacturer specifications available in India market.
 * This serves as the reference baseline for battery health predictions.
 */

export const vehicleCategories = [
  {
    id: 'two_wheeler',
    label: 'Two-Wheeler',
    icon: 'Bike',
    description: 'Electric scooters & motorcycles',
  },
  {
    id: 'three_wheeler',
    label: 'Three-Wheeler',
    icon: 'Truck',
    description: 'Electric auto-rickshaws & cargo',
  },
  {
    id: 'four_wheeler',
    label: 'Four-Wheeler',
    icon: 'Car',
    description: 'Electric cars & SUVs',
  },
  {
    id: 'bus_heavy',
    label: 'Bus / Heavy Vehicle',
    icon: 'Bus',
    description: 'Electric buses & commercial vehicles',
  },
];

/**
 * Real EV battery specifications by manufacturer and model.
 * Each entry includes the official battery specs from the manufacturer.
 *
 * Fields:
 * - batteryCapacity (kWh): Total battery pack energy capacity
 * - voltage (V): Nominal system voltage
 * - expectedCycles: Manufacturer-rated cycle life to 80% SOH
 * - typicalRange (km): Official claimed range
 * - warrantyYears: Battery warranty period
 * - warrantyKm: Battery warranty km limit
 * - batteryType: Chemistry type
 * - maxChargingPower (kW): Maximum DC fast charging power
 * - estimatedLifeYears: Typical expected battery life
 */
export const vehicleDatabase = {
  two_wheeler: [
    {
      make: 'Ola Electric',
      models: [
        {
          model: 'S1 Air',
          yearRange: '2022-2024',
          batteryCapacity: 2.5,
          voltage: 48,
          expectedCycles: 1000,
          typicalRange: 101,
          warrantyYears: 3,
          warrantyKm: 30000,
          batteryType: 'LFP',
          maxChargingPower: 1.2,
          estimatedLifeYears: 5,
        },
        {
          model: 'S1',
          yearRange: '2021-2023',
          batteryCapacity: 3.97,
          voltage: 48,
          expectedCycles: 1200,
          typicalRange: 181,
          warrantyYears: 3,
          warrantyKm: 30000,
          batteryType: 'LFP',
          maxChargingPower: 1.2,
          estimatedLifeYears: 5,
        },
        {
          model: 'S1 Pro',
          yearRange: '2022-2024',
          batteryCapacity: 4.0,
          voltage: 48,
          expectedCycles: 1200,
          typicalRange: 195,
          warrantyYears: 3,
          warrantyKm: 30000,
          batteryType: 'LFP',
          maxChargingPower: 1.5,
          estimatedLifeYears: 5,
        },
        {
          model: 'S1 X',
          yearRange: '2023-2024',
          batteryCapacity: 3.0,
          voltage: 48,
          expectedCycles: 1000,
          typicalRange: 151,
          warrantyYears: 3,
          warrantyKm: 30000,
          batteryType: 'LFP',
          maxChargingPower: 1.2,
          estimatedLifeYears: 5,
        },
      ],
    },
    {
      make: 'Ather Energy',
      models: [
        {
          model: '450X',
          yearRange: '2020-2024',
          batteryCapacity: 3.7,
          voltage: 51.8,
          expectedCycles: 1200,
          typicalRange: 150,
          warrantyYears: 3,
          warrantyKm: 30000,
          batteryType: 'NMC',
          maxChargingPower: 1.3,
          estimatedLifeYears: 5,
        },
        {
          model: '450 Plus',
          yearRange: '2020-2023',
          batteryCapacity: 2.9,
          voltage: 51.8,
          expectedCycles: 1200,
          typicalRange: 115,
          warrantyYears: 3,
          warrantyKm: 30000,
          batteryType: 'NMC',
          maxChargingPower: 1.0,
          estimatedLifeYears: 5,
        },
        {
          model: '450 Apex',
          yearRange: '2024',
          batteryCapacity: 3.7,
          voltage: 51.8,
          expectedCycles: 1300,
          typicalRange: 157,
          warrantyYears: 5,
          warrantyKm: 60000,
          batteryType: 'NMC',
          maxChargingPower: 1.3,
          estimatedLifeYears: 6,
        },
        {
          model: 'Rizta',
          yearRange: '2024',
          batteryCapacity: 3.7,
          voltage: 48,
          expectedCycles: 1500,
          typicalRange: 160,
          warrantyYears: 5,
          warrantyKm: 50000,
          batteryType: 'LFP',
          maxChargingPower: 1.3,
          estimatedLifeYears: 7,
        },
      ],
    },
    {
      make: 'Bajaj Auto',
      models: [
        {
          model: 'Chetak Premium',
          yearRange: '2022-2024',
          batteryCapacity: 3.0,
          voltage: 48,
          expectedCycles: 1000,
          typicalRange: 113,
          warrantyYears: 3,
          warrantyKm: 30000,
          batteryType: 'LFP',
          maxChargingPower: 0.9,
          estimatedLifeYears: 5,
        },
        {
          model: 'Chetak Urbane',
          yearRange: '2022-2024',
          batteryCapacity: 2.9,
          voltage: 48,
          expectedCycles: 1000,
          typicalRange: 108,
          warrantyYears: 3,
          warrantyKm: 30000,
          batteryType: 'LFP',
          maxChargingPower: 0.9,
          estimatedLifeYears: 5,
        },
      ],
    },
    {
      make: 'TVS Motor',
      models: [
        {
          model: 'iQube Electric',
          yearRange: '2020-2023',
          batteryCapacity: 3.04,
          voltage: 51.8,
          expectedCycles: 1000,
          typicalRange: 100,
          warrantyYears: 3,
          warrantyKm: 30000,
          batteryType: 'NMC',
          maxChargingPower: 0.75,
          estimatedLifeYears: 5,
        },
        {
          model: 'iQube S',
          yearRange: '2022-2024',
          batteryCapacity: 3.04,
          voltage: 51.8,
          expectedCycles: 1000,
          typicalRange: 100,
          warrantyYears: 5,
          warrantyKm: 50000,
          batteryType: 'NMC',
          maxChargingPower: 0.75,
          estimatedLifeYears: 5,
        },
        {
          model: 'iQube ST',
          yearRange: '2022-2024',
          batteryCapacity: 5.1,
          voltage: 51.8,
          expectedCycles: 1200,
          typicalRange: 175,
          warrantyYears: 5,
          warrantyKm: 50000,
          batteryType: 'NMC',
          maxChargingPower: 1.2,
          estimatedLifeYears: 6,
        },
      ],
    },
    {
      make: 'Simple Energy',
      models: [
        {
          model: 'One',
          yearRange: '2023-2024',
          batteryCapacity: 8.5,
          voltage: 72,
          expectedCycles: 1500,
          typicalRange: 236,
          warrantyYears: 5,
          warrantyKm: 60000,
          batteryType: 'NMC',
          maxChargingPower: 3.0,
          estimatedLifeYears: 7,
        },
      ],
    },
    {
      make: 'Ampere',
      models: [
        {
          model: 'Magnus',
          yearRange: '2022-2024',
          batteryCapacity: 2.5,
          voltage: 48,
          expectedCycles: 800,
          typicalRange: 100,
          warrantyYears: 3,
          warrantyKm: 30000,
          batteryType: 'LFP',
          maxChargingPower: 0.6,
          estimatedLifeYears: 4,
        },
        {
          model: 'Reo Plus',
          yearRange: '2020-2023',
          batteryCapacity: 1.8,
          voltage: 48,
          expectedCycles: 700,
          typicalRange: 70,
          warrantyYears: 2,
          warrantyKm: 20000,
          batteryType: 'Lead Acid',
          maxChargingPower: 0.3,
          estimatedLifeYears: 3,
        },
      ],
    },
    {
      make: 'Hero Electric',
      models: [
        {
          model: 'Optima CX',
          yearRange: '2019-2023',
          batteryCapacity: 1.8,
          voltage: 48,
          expectedCycles: 700,
          typicalRange: 75,
          warrantyYears: 2,
          warrantyKm: 20000,
          batteryType: 'Lead Acid',
          maxChargingPower: 0.3,
          estimatedLifeYears: 3,
        },
        {
          model: 'Atria',
          yearRange: '2022-2023',
          batteryCapacity: 3.0,
          voltage: 60,
          expectedCycles: 1000,
          typicalRange: 115,
          warrantyYears: 3,
          warrantyKm: 30000,
          batteryType: 'LFP',
          maxChargingPower: 0.6,
          estimatedLifeYears: 5,
        },
      ],
    },
    {
      make: 'Okinawa',
      models: [
        {
          model: 'Praise Pro',
          yearRange: '2021-2023',
          batteryCapacity: 2.5,
          voltage: 60,
          expectedCycles: 800,
          typicalRange: 110,
          warrantyYears: 3,
          warrantyKm: 30000,
          batteryType: 'LFP',
          maxChargingPower: 0.6,
          estimatedLifeYears: 4,
        },
        {
          model: 'iPraise+',
          yearRange: '2022-2024',
          batteryCapacity: 3.0,
          voltage: 60,
          expectedCycles: 1000,
          typicalRange: 130,
          warrantyYears: 3,
          warrantyKm: 30000,
          batteryType: 'LFP',
          maxChargingPower: 0.6,
          estimatedLifeYears: 5,
        },
      ],
    },
  ],
  three_wheeler: [
    {
      make: 'Mahindra Electric',
      models: [
        {
          model: 'Treo',
          yearRange: '2020-2024',
          batteryCapacity: 7.4,
          voltage: 72,
          expectedCycles: 1500,
          typicalRange: 130,
          warrantyYears: 3,
          warrantyKm: 50000,
          batteryType: 'LFP',
          maxChargingPower: 1.5,
          estimatedLifeYears: 7,
        },
        {
          model: 'Treo Zor (Cargo)',
          yearRange: '2020-2024',
          batteryCapacity: 9.0,
          voltage: 72,
          expectedCycles: 1500,
          typicalRange: 150,
          warrantyYears: 3,
          warrantyKm: 50000,
          batteryType: 'LFP',
          maxChargingPower: 1.5,
          estimatedLifeYears: 7,
        },
      ],
    },
    {
      make: 'Piaggio',
      models: [
        {
          model: 'Ape E-City',
          yearRange: '2021-2024',
          batteryCapacity: 8.6,
          voltage: 72,
          expectedCycles: 1500,
          typicalRange: 110,
          warrantyYears: 3,
          warrantyKm: 50000,
          batteryType: 'LFP',
          maxChargingPower: 1.5,
          estimatedLifeYears: 7,
        },
        {
          model: 'Ape E-Xtra',
          yearRange: '2021-2024',
          batteryCapacity: 10.6,
          voltage: 72,
          expectedCycles: 1500,
          typicalRange: 140,
          warrantyYears: 3,
          warrantyKm: 50000,
          batteryType: 'LFP',
          maxChargingPower: 2.0,
          estimatedLifeYears: 7,
        },
      ],
    },
    {
      make: 'Bajaj Auto',
      models: [
        {
          model: 'RE EV',
          yearRange: '2022-2024',
          batteryCapacity: 6.0,
          voltage: 72,
          expectedCycles: 1200,
          typicalRange: 95,
          warrantyYears: 3,
          warrantyKm: 40000,
          batteryType: 'LFP',
          maxChargingPower: 1.2,
          estimatedLifeYears: 5,
        },
      ],
    },
  ],
  four_wheeler: [
    {
      make: 'Tata Motors',
      models: [
        {
          model: 'Nexon EV Prime',
          yearRange: '2020-2023',
          batteryCapacity: 30.2,
          voltage: 320,
          expectedCycles: 2000,
          typicalRange: 312,
          warrantyYears: 8,
          warrantyKm: 160000,
          batteryType: 'LFP',
          maxChargingPower: 30,
          estimatedLifeYears: 10,
        },
        {
          model: 'Nexon EV Max',
          yearRange: '2022-2023',
          batteryCapacity: 40.5,
          voltage: 320,
          expectedCycles: 2000,
          typicalRange: 437,
          warrantyYears: 8,
          warrantyKm: 160000,
          batteryType: 'NMC',
          maxChargingPower: 50,
          estimatedLifeYears: 10,
        },
        {
          model: 'Nexon EV LR',
          yearRange: '2023-2024',
          batteryCapacity: 40.5,
          voltage: 320,
          expectedCycles: 2500,
          typicalRange: 465,
          warrantyYears: 8,
          warrantyKm: 160000,
          batteryType: 'NMC',
          maxChargingPower: 60,
          estimatedLifeYears: 12,
        },
        {
          model: 'Nexon EV MR',
          yearRange: '2023-2024',
          batteryCapacity: 30.0,
          voltage: 320,
          expectedCycles: 2500,
          typicalRange: 325,
          warrantyYears: 8,
          warrantyKm: 160000,
          batteryType: 'LFP',
          maxChargingPower: 40,
          estimatedLifeYears: 12,
        },
        {
          model: 'Tiago EV',
          yearRange: '2023-2024',
          batteryCapacity: 19.2,
          voltage: 260,
          expectedCycles: 2000,
          typicalRange: 250,
          warrantyYears: 8,
          warrantyKm: 120000,
          batteryType: 'LFP',
          maxChargingPower: 25,
          estimatedLifeYears: 8,
        },
        {
          model: 'Tiago EV LR',
          yearRange: '2023-2024',
          batteryCapacity: 24.0,
          voltage: 260,
          expectedCycles: 2000,
          typicalRange: 315,
          warrantyYears: 8,
          warrantyKm: 120000,
          batteryType: 'LFP',
          maxChargingPower: 25,
          estimatedLifeYears: 8,
        },
        {
          model: 'Punch EV',
          yearRange: '2024',
          batteryCapacity: 25.0,
          voltage: 260,
          expectedCycles: 2500,
          typicalRange: 315,
          warrantyYears: 8,
          warrantyKm: 160000,
          batteryType: 'LFP',
          maxChargingPower: 40,
          estimatedLifeYears: 10,
        },
        {
          model: 'Punch EV LR',
          yearRange: '2024',
          batteryCapacity: 35.0,
          voltage: 320,
          expectedCycles: 2500,
          typicalRange: 421,
          warrantyYears: 8,
          warrantyKm: 160000,
          batteryType: 'NMC',
          maxChargingPower: 50,
          estimatedLifeYears: 10,
        },
        {
          model: 'Curvv EV',
          yearRange: '2024',
          batteryCapacity: 45.0,
          voltage: 320,
          expectedCycles: 2500,
          typicalRange: 500,
          warrantyYears: 8,
          warrantyKm: 160000,
          batteryType: 'NMC',
          maxChargingPower: 70,
          estimatedLifeYears: 12,
        },
      ],
    },
    {
      make: 'MG Motor',
      models: [
        {
          model: 'ZS EV (Standard)',
          yearRange: '2020-2022',
          batteryCapacity: 44.5,
          voltage: 380,
          expectedCycles: 2000,
          typicalRange: 340,
          warrantyYears: 8,
          warrantyKm: 150000,
          batteryType: 'NMC',
          maxChargingPower: 50,
          estimatedLifeYears: 10,
        },
        {
          model: 'ZS EV (Long Range)',
          yearRange: '2022-2024',
          batteryCapacity: 50.3,
          voltage: 380,
          expectedCycles: 2000,
          typicalRange: 461,
          warrantyYears: 8,
          warrantyKm: 150000,
          batteryType: 'NMC',
          maxChargingPower: 50,
          estimatedLifeYears: 10,
        },
        {
          model: 'Comet EV',
          yearRange: '2023-2024',
          batteryCapacity: 17.3,
          voltage: 240,
          expectedCycles: 1500,
          typicalRange: 230,
          warrantyYears: 8,
          warrantyKm: 100000,
          batteryType: 'LFP',
          maxChargingPower: 15,
          estimatedLifeYears: 8,
        },
        {
          model: 'Windsor EV',
          yearRange: '2024',
          batteryCapacity: 50.3,
          voltage: 380,
          expectedCycles: 2500,
          typicalRange: 500,
          warrantyYears: 8,
          warrantyKm: 150000,
          batteryType: 'NMC',
          maxChargingPower: 50,
          estimatedLifeYears: 12,
        },
      ],
    },
    {
      make: 'Hyundai',
      models: [
        {
          model: 'Kona Electric',
          yearRange: '2019-2023',
          batteryCapacity: 39.2,
          voltage: 360,
          expectedCycles: 2000,
          typicalRange: 452,
          warrantyYears: 8,
          warrantyKm: 160000,
          batteryType: 'NMC',
          maxChargingPower: 50,
          estimatedLifeYears: 10,
        },
        {
          model: 'IONIQ 5',
          yearRange: '2023-2024',
          batteryCapacity: 72.6,
          voltage: 697,
          expectedCycles: 2500,
          typicalRange: 631,
          warrantyYears: 8,
          warrantyKm: 160000,
          batteryType: 'NMC',
          maxChargingPower: 350,
          estimatedLifeYears: 12,
        },
        {
          model: 'Creta EV',
          yearRange: '2024',
          batteryCapacity: 42.0,
          voltage: 360,
          expectedCycles: 2500,
          typicalRange: 473,
          warrantyYears: 8,
          warrantyKm: 160000,
          batteryType: 'NMC',
          maxChargingPower: 60,
          estimatedLifeYears: 12,
        },
      ],
    },
    {
      make: 'BYD India',
      models: [
        {
          model: 'Atto 3 (Standard)',
          yearRange: '2022-2024',
          batteryCapacity: 49.92,
          voltage: 403,
          expectedCycles: 3000,
          typicalRange: 410,
          warrantyYears: 8,
          warrantyKm: 160000,
          batteryType: 'LFP (Blade)',
          maxChargingPower: 70,
          estimatedLifeYears: 12,
        },
        {
          model: 'Atto 3 (Extended)',
          yearRange: '2023-2024',
          batteryCapacity: 60.48,
          voltage: 403,
          expectedCycles: 3000,
          typicalRange: 521,
          warrantyYears: 8,
          warrantyKm: 160000,
          batteryType: 'LFP (Blade)',
          maxChargingPower: 70,
          estimatedLifeYears: 12,
        },
        {
          model: 'e6',
          yearRange: '2021-2024',
          batteryCapacity: 71.7,
          voltage: 403,
          expectedCycles: 3000,
          typicalRange: 520,
          warrantyYears: 8,
          warrantyKm: 160000,
          batteryType: 'LFP (Blade)',
          maxChargingPower: 60,
          estimatedLifeYears: 12,
        },
        {
          model: 'Seal',
          yearRange: '2024',
          batteryCapacity: 82.56,
          voltage: 537,
          expectedCycles: 3000,
          typicalRange: 700,
          warrantyYears: 8,
          warrantyKm: 160000,
          batteryType: 'LFP (Blade)',
          maxChargingPower: 150,
          estimatedLifeYears: 12,
        },
      ],
    },
    {
      make: 'Mahindra',
      models: [
        {
          model: 'XUV400 (EC)',
          yearRange: '2023-2024',
          batteryCapacity: 34.5,
          voltage: 320,
          expectedCycles: 2000,
          typicalRange: 375,
          warrantyYears: 8,
          warrantyKm: 160000,
          batteryType: 'NMC',
          maxChargingPower: 40,
          estimatedLifeYears: 10,
        },
        {
          model: 'XUV400 (EL)',
          yearRange: '2023-2024',
          batteryCapacity: 39.4,
          voltage: 320,
          expectedCycles: 2000,
          typicalRange: 456,
          warrantyYears: 8,
          warrantyKm: 160000,
          batteryType: 'NMC',
          maxChargingPower: 50,
          estimatedLifeYears: 10,
        },
        {
          model: 'BE 6e',
          yearRange: '2024',
          batteryCapacity: 59.0,
          voltage: 400,
          expectedCycles: 3000,
          typicalRange: 550,
          warrantyYears: 8,
          warrantyKm: 160000,
          batteryType: 'NMC',
          maxChargingPower: 120,
          estimatedLifeYears: 12,
        },
        {
          model: 'XEV 9e',
          yearRange: '2024',
          batteryCapacity: 59.0,
          voltage: 400,
          expectedCycles: 3000,
          typicalRange: 600,
          warrantyYears: 8,
          warrantyKm: 160000,
          batteryType: 'NMC',
          maxChargingPower: 120,
          estimatedLifeYears: 12,
        },
      ],
    },
    {
      make: 'Citroen',
      models: [
        {
          model: 'eC3',
          yearRange: '2023-2024',
          batteryCapacity: 29.2,
          voltage: 336,
          expectedCycles: 2000,
          typicalRange: 320,
          warrantyYears: 8,
          warrantyKm: 100000,
          batteryType: 'LFP',
          maxChargingPower: 30,
          estimatedLifeYears: 8,
        },
      ],
    },
    {
      make: 'Volvo',
      models: [
        {
          model: 'XC40 Recharge',
          yearRange: '2022-2024',
          batteryCapacity: 69.0,
          voltage: 400,
          expectedCycles: 2000,
          typicalRange: 418,
          warrantyYears: 8,
          warrantyKm: 160000,
          batteryType: 'NMC',
          maxChargingPower: 150,
          estimatedLifeYears: 10,
        },
        {
          model: 'C40 Recharge',
          yearRange: '2023-2024',
          batteryCapacity: 69.0,
          voltage: 400,
          expectedCycles: 2000,
          typicalRange: 440,
          warrantyYears: 8,
          warrantyKm: 160000,
          batteryType: 'NMC',
          maxChargingPower: 150,
          estimatedLifeYears: 10,
        },
      ],
    },
    {
      make: 'BMW',
      models: [
        {
          model: 'i4 eDrive35',
          yearRange: '2023-2024',
          batteryCapacity: 70.0,
          voltage: 400,
          expectedCycles: 2000,
          typicalRange: 483,
          warrantyYears: 8,
          warrantyKm: 160000,
          batteryType: 'NMC',
          maxChargingPower: 200,
          estimatedLifeYears: 10,
        },
        {
          model: 'iX1',
          yearRange: '2023-2024',
          batteryCapacity: 64.7,
          voltage: 400,
          expectedCycles: 2000,
          typicalRange: 440,
          warrantyYears: 8,
          warrantyKm: 160000,
          batteryType: 'NMC',
          maxChargingPower: 130,
          estimatedLifeYears: 10,
        },
        {
          model: 'i7',
          yearRange: '2023-2024',
          batteryCapacity: 101.7,
          voltage: 400,
          expectedCycles: 2000,
          typicalRange: 650,
          warrantyYears: 8,
          warrantyKm: 160000,
          batteryType: 'NMC',
          maxChargingPower: 195,
          estimatedLifeYears: 10,
        },
      ],
    },
    {
      make: 'Mercedes-Benz',
      models: [
        {
          model: 'EQS 580',
          yearRange: '2022-2024',
          batteryCapacity: 107.8,
          voltage: 400,
          expectedCycles: 2000,
          typicalRange: 857,
          warrantyYears: 10,
          warrantyKm: 250000,
          batteryType: 'NMC',
          maxChargingPower: 200,
          estimatedLifeYears: 12,
        },
        {
          model: 'EQB',
          yearRange: '2023-2024',
          batteryCapacity: 66.5,
          voltage: 400,
          expectedCycles: 2000,
          typicalRange: 423,
          warrantyYears: 8,
          warrantyKm: 160000,
          batteryType: 'NMC',
          maxChargingPower: 100,
          estimatedLifeYears: 10,
        },
      ],
    },
  ],
  bus_heavy: [
    {
      make: 'Olectra Greentech',
      models: [
        {
          model: 'K9 (12m Bus)',
          yearRange: '2020-2024',
          batteryCapacity: 310,
          voltage: 640,
          expectedCycles: 4000,
          typicalRange: 200,
          warrantyYears: 5,
          warrantyKm: 200000,
          batteryType: 'LFP',
          maxChargingPower: 150,
          estimatedLifeYears: 10,
        },
        {
          model: '9m Mini Bus',
          yearRange: '2022-2024',
          batteryCapacity: 186,
          voltage: 540,
          expectedCycles: 4000,
          typicalRange: 150,
          warrantyYears: 5,
          warrantyKm: 200000,
          batteryType: 'LFP',
          maxChargingPower: 100,
          estimatedLifeYears: 10,
        },
      ],
    },
    {
      make: 'PMI Electro',
      models: [
        {
          model: 'Fusion (12m Bus)',
          yearRange: '2021-2024',
          batteryCapacity: 250,
          voltage: 640,
          expectedCycles: 4000,
          typicalRange: 180,
          warrantyYears: 5,
          warrantyKm: 200000,
          batteryType: 'LFP',
          maxChargingPower: 120,
          estimatedLifeYears: 10,
        },
      ],
    },
    {
      make: 'JBM Auto',
      models: [
        {
          model: '9m Mini EV Bus',
          yearRange: '2022-2024',
          batteryCapacity: 165,
          voltage: 540,
          expectedCycles: 4000,
          typicalRange: 160,
          warrantyYears: 5,
          warrantyKm: 150000,
          batteryType: 'LFP',
          maxChargingPower: 80,
          estimatedLifeYears: 10,
        },
        {
          model: '12m EV Bus',
          yearRange: '2021-2024',
          batteryCapacity: 280,
          voltage: 640,
          expectedCycles: 4000,
          typicalRange: 220,
          warrantyYears: 5,
          warrantyKm: 200000,
          batteryType: 'LFP',
          maxChargingPower: 150,
          estimatedLifeYears: 10,
        },
      ],
    },
    {
      make: 'Ashok Leyland',
      models: [
        {
          model: 'Switch EiV 12',
          yearRange: '2022-2024',
          batteryCapacity: 231,
          voltage: 540,
          expectedCycles: 4000,
          typicalRange: 200,
          warrantyYears: 5,
          warrantyKm: 200000,
          batteryType: 'LFP',
          maxChargingPower: 120,
          estimatedLifeYears: 10,
        },
        {
          model: 'Switch EiV 9',
          yearRange: '2022-2024',
          batteryCapacity: 150,
          voltage: 540,
          expectedCycles: 4000,
          typicalRange: 150,
          warrantyYears: 5,
          warrantyKm: 150000,
          batteryType: 'LFP',
          maxChargingPower: 80,
          estimatedLifeYears: 10,
        },
      ],
    },
  ],
};

/**
 * Get all makes for a vehicle category
 */
export function getMakesForCategory(categoryId) {
  return vehicleDatabase[categoryId]?.map((entry) => entry.make) ?? [];
}

/**
 * Get all models for a specific make within a category
 */
export function getModelsForMake(categoryId, makeName) {
  const makeEntry = vehicleDatabase[categoryId]?.find((entry) => entry.make === makeName);
  return makeEntry?.models ?? [];
}

/**
 * Get the battery spec for a specific vehicle model
 */
export function getVehicleSpec(categoryId, makeName, modelName) {
  const models = getModelsForMake(categoryId, makeName);
  return models.find((m) => m.model === modelName) ?? null;
}

/**
 * Get the default battery fields pre-filled based on vehicle spec
 */
export function getDefaultBatteryValues(vehicleSpec) {
  if (!vehicleSpec) return {};
  return {
    batteryCapacity: vehicleSpec.batteryCapacity,
    voltage: vehicleSpec.voltage,
    expectedCycles: vehicleSpec.expectedCycles,
    typicalRange: vehicleSpec.typicalRange,
    estimatedLifeYears: vehicleSpec.estimatedLifeYears,
  };
}

/**
 * Categorize vehicle type for model routing
 */
export function getVehicleTypeCode(categoryId) {
  const codes = {
    two_wheeler: 'BIKE',
    three_wheeler: 'AUTO',
    four_wheeler: 'CAR',
    bus_heavy: 'BUS',
  };
  return codes[categoryId] || 'CAR';
}